### ISSUE TITLE
attempt to call field 'toPixels' (a nil value)

### ISSUE THREAD

**Issue by taxilly** [tavuntu/gooi#10]
Using LOVE 0.9.1
In main.lua, [https://github.com/twentytwoo/plottr](https://github.com/twentytwoo/plottr)

![2017-05-14-163018_1366x768_scrot](https://cloud.githubusercontent.com/assets/13081443/26035353/ad4b8048-38c2-11e7-993e-e3b23a5aaf0f.png)

**Comment by gustavostuff** [comment]
[that function](https://love2d.org/wiki/love.window.toPixels) was added in LÖVE 0.9.2, the latest version of GOOi works with 0.10.2 (I haven't tested it on 0.10.1 and 0.10.0)
