### ISSUE TITLE
Image background for buttons, sliders etc...

### ISSUE THREAD

**Issue by MrStevns** [tavuntu/gooi#12]
Being able to apply images as backgrounds to buttons, sliders and such would be quite handy. I'm trying to look into this myself atm. as I need my sliders to have a gradient background color for my interface.

Keep up the good work 👍

**Comment by gustavostuff** [comment]
Thanks for the idea, that will definitely be in version 0.0.5

**Comment by gustavostuff** [comment]
I just uploaded version 0.0.5, this feature is supported now :)
