### ISSUE TITLE
exit button fails from example one

### ISSUE THREAD

**Issue by ankit-g** [tavuntu/gooi#15]
Error: gooi/gooi.lua:2328: attempt to index field 'style' (a nil value)
stack traceback:
	gooi/gooi.lua:2328: in function 'getFont'
	gooi/gooi.lua:1993: in function 'draw'
	main.lua:133: in function 'draw'
	[string "boot.lua"]:468: in function <[string "boot.lua"]:436>
	[C]: in function 'xpcall'
AL lib: (EE) alc_cleanup: 1 device not closed

--> I'm using this code for one of my projects, I found this issue there.

I've made fixed it for my project if you want I can submit the patch.

**Comment by gustavostuff** [comment]
Sure, please make a pull request.
