### ISSUE TITLE
phone devices `setTextInput` with area parameters

### ISSUE THREAD

**Issue by ImagicTheCat** [tavuntu/gooi#24]
I don't know if the project is still active, but `setTextInput` now have parameters for the input area to make sure the virtual keyboard will not hide the field (tested and working on android 8.1).

**Comment by gustavostuff** [comment]
Thanks for the heads up. I haven't been really active with this project but I try to at least keep up with love versions (and in many cases people have helped me out with pull requests). I'm not sure if I'll have time to make this change soon so feel free to make one.

**Comment by ImagicTheCat** [comment]
Okay, I will probably do that.
