### ISSUE TITLE
keep button pressed perform constant action

### ISSUE THREAD

**Issue by pankiwi** [tavuntu/gooi#31]
I was trying the example that I leave but I can't find in the wiki that the actions of the buttons don't stop until I stop pressing the button

**Comment by gustavostuff** [comment]
All components have `:onPress()`,  `:onRelease()` and `:onMoved()` (look at [this file](https://github.com/tavuntu/gooi/blob/master/gooi/component.lua)). But you're right, that's not in the docs, my fault.

**Comment by pankiwi** [comment]
thx
