### ISSUE TITLE
Buttons not scaling icon

### ISSUE THREAD

**Issue by ArchAngel075** [tavuntu/gooi#7]
Might not be intended.
Excuse typos and shorthandedness. Uaing mobile device. Will improve tonight

Changing the drawing of Button.icon touse size of the component will better constrain the  clickable space of the button to what is the actual image. Although a separate field iconWidth (iw) and iconHeight (ih) can be get and set for button icon size specifically if one wants the size to he independant.

Use the following in place of sx,sy of the love.draw () call in button:draw ()
sx = self.w/self.icon:getWidth()
sy = self.h/self.icon:getHeight()

The self.# and get# might jeed to be swapped to achieve the scaling. Im not at pc at the moment but my home device has this setup on modified GOOI code

**Comment by gustavostuff** [comment]
Icons are not intended to be scaled in buttons/labels, I''ll have that in mind though :)

**Comment by trelemar** [comment]
Yeah id let scaling be a canvas thing. Or the user should have different sized icons depending on the screen's dpi

**Comment by gustavostuff** [comment]
̶s̶c̶a̶l̶i̶n̶g̶ ̶i̶s̶ ̶a̶c̶t̶u̶a̶l̶l̶y̶ ̶a̶ ̶c̶a̶n̶v̶a̶s̶ ̶t̶h̶i̶n̶g̶ ̶(̶y̶o̶u̶ ̶c̶a̶n̶ ̶s̶e̶e̶ ̶i̶t̶ ̶i̶n̶ ̶d̶e̶m̶o̶_̶c̶a̶n̶v̶a̶s̶.̶l̶o̶v̶e̶ ̶o̶n̶ ̶t̶h̶e̶ ̶r̶e̶p̶o̶)̶, (never mind this, I got it wrong). For this icon issue maybe a function like this one would be useful? ```gooi.scaleIcons(true)``` so the icon will have a size proportional to the component height, always.

**Comment by trelemar** [comment]
That could work, or maybe include the bool into a style attribute? But default to false.

**Comment by gustavostuff** [comment]
That makes sense.

**Comment by ArchAngel075** [comment]
that would be ok i guess. as for my current project i intend to scale input images to the element size, but im probably going to modify to have separate sx,y fields. often i need to scale the icon to the button, other times I need to scale to an certain size and then offset the icon with text ([icon .. padding .. text] etc)
Its more a choice thing, but if it is cumbersome then i am fine with receiving updated GOOi and modifying my needed code.

anyhow off topic, again my suggestion was sx,sy values to specify the scale itself, ill use whatever is added/changed though.

**Comment by gustavostuff** [comment]
I have decided to not scale icons, not right now at least, if different sizes are needed then I'd recommend the usual, using different images (16x16, 32x32...) and choose the right one for the current resolution. Another option would be to simply scale the icon in an image editor because, if the image is too small and and pixel-perfect scaling is required, then some calculations would be needed inside GÖÖi, but I'm still thinking it's better to manage this externally.
