### ISSUE TITLE
nested panel example

### ISSUE THREAD

**Issue by fnaith** [tavuntu/gooi#9]
Because the limitation about "panel cannot inside panel" is gone, I try to modify main.lua and add pGame into pGrid.

In my mind, the widget inside pGame will auto resize(or clip) for fixing grid layout.

But I totally mess up as following image:

![default](https://cloud.githubusercontent.com/assets/11421034/22585980/65f0b5b4-ea35-11e6-8c03-d9e683bb0440.PNG)

I think it is not bug, but a nested panel demo maybe helpful.

**Comment by gustavostuff** [comment]
My bad, those limitations are still part of GÖÖi, I accidentally removed the list in the last update, I added it again.

**Comment by fnaith** [comment]
Got it!
